### ISSUE TITLE
examples for different middleware types

### ISSUE THREAD

**Issue by ChopperLee2011** [strongloop/loopback-faq-middleware#5]
The online doc for middleware example is incomplete, so could this repo fill it?  For me, I need help for register a routing middleware by editing server/middleware.json.

**Comment by hacksparrow** [comment]
@ChopperLee2011 thanks for bringing this to our notice. You can refer to `server/middleware.json` of the [loopback-example-app](https://github.com/strongloop/loopback-example-app) for an example of a routing middleware (`loopback#rest`).

@crandmck looks like we need to do some work here?

**Comment by crandmck** [comment]
[The doc](https://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Routingmiddleware) actually says _not_ to use `middleware.json` for routing middleware:
> You can register routes in middleware.json, but standard practice is to do so in server.js or a boot script, as you do with Express.  For more information, see Using the Express API.

And the referenced section, [Using the Express API](https://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-UsingtheExpressAPI), has quite a bit of detail.

@ChopperLee2011 why do you say it's incomplete, and specifically what more would you like to see?

**Comment by ChopperLee2011** [comment]
@hacksparrow it helps, thank u
@crandmck for example: 
 - Index, the last links to middleware example is going to noplace.
 - Overview part, can not go to examples except the `example of static middleware`, make me think the examples just not exists.
 - Specifying/Registering  a middleware, sorry i can find your quoted words, especially the 'NOT TO USE'. Btw, i think it is good to have a clear directory structure and a configure file for custom middleware develop and share.
And i will be appreciate  if Middleware type and phases can be in one picture for more clear view. Of curse, the link of demo for different middleware type could work.

**Comment by crandmck** [comment]
@ChopperLee2011 Just to be sure we're talking about the same thing, are you referring to https://docs.strongloop.com/display/LB/Defining+middleware ?

If so, then most of the issues you note seem to be due to intrapage links not working for you.  What browser are you using?  I think there may be some browser-specific issues with Confluence intrapage links.

> Specifying/Registering a middleware, sorry i can find your quoted words, especially the 'NOT TO USE'.
It doesn't use those words, because you can use `middleware.json`, but it says "standard practice is ..."
I linked to the section: https://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Routingmiddleware, but here is a screenshot:

![2015-09-21_1632](https://cloud.githubusercontent.com/assets/2925364/10007992/e9443fcc-607e-11e5-874f-d13653c63670.png)

**Comment by ChopperLee2011** [comment]
@crandmck : sorry, maybe i not describe it clear. i mean https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Routingmiddleware
https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Pre-processingmiddleware
can not open

**Comment by crandmck** [comment]
@ChopperLee2011 Thanks for clarifying! There was a very strange, obscure error with the Confluence wiki that made those sections visible only if you were logged in to the wiki (which normally a reader would not be).  I believe I fixed it, so you should be able to see those sections now.  Let me know if there are any further issues.

**Comment by ChopperLee2011** [comment]
@crandmck thanks, it can work, closing this issue.
